name: Test de Conexion
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # Actualizado de v3 a v4
      - name: Configurar Python
        uses: actions/setup-python@v5 # Actualizado de v4 a v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: pip install requests
      - name: Run test
        run: python test_conexion.py
