name: Pipeline Semanal MEL-TP

on:
  schedule:
    # 09:00 AM Argentina (UTC-3) los días 5 y 28 de cada mes
    - cron: '0 12 5,28 * *'
  workflow_dispatch: 

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install holidays  # Aseguramos la librería de feriados

      # Los pasos de ejecución de scripts se mantienen igual...
      # El script de Python decidirá si procesar o no según el calendario.
